# Generated by Django 4.1.3 on 2022-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_image'),
        ),
    ]
